[package]
name = "raytrace"
version.workspace = true
include.workspace = true
edition.workspace = true
publish = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image.workspace = true
