[workspace]
workspace.resolver = "2"

members = [
    "raytrace",
    "dev_run"
]

[workspace.package]
version = "0.0.10"
include = ["Cargo.toml"]
edition = "2021"

[workspace.dependencies]
image = "0.24.7"